/* Generated By:JavaCC: Do not edit this line. OpeningTimeCompilerConstants.java */
package org.openstreetmap.josm.plugins.ohe.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OpeningTimeCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 1;
  /** RegularExpression Id. */
  int WEEKDAY = 2;
  /** RegularExpression Id. */
  int PLUS = 3;
  /** RegularExpression Id. */
  int OFF = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<DIGIT>",
    "<WEEKDAY>",
    "\"+\"",
    "\"off\"",
    "\"24/7\"",
    "\"; \"",
    "\" \"",
    "\",\"",
    "\"-\"",
    "\":\"",
  };

}
