/* Generated By:JavaCC: Do not edit this line. ParamStringScannerConstants.java */
package org.openstreetmap.josm.plugins.roadsigns.javacc;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParamStringScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 1;
  /** RegularExpression Id. */
  int ESC = 2;
  /** RegularExpression Id. */
  int REST = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ID>",
    "<ESC>",
    "<REST>",
  };

}
