//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.10 at 10:24:05 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openstreetmap.josm.plugins.dataimport.io.tcx;
